#version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wikonia-app
    ports:
      - "8081:8000"
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    command: >
      php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: wikonia-db
    #restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: wikonia
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: wikonia-pma
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data: