blank_issues_enabled: false

contact_links:
  - name: 📬 Support-Anfragen / Ticketsystem
    url: https://support.wikonia.net
    about: Nutze bitte unser zentrales Ticketsystem für allgemeine Anfragen, Bugs und Supportthemen außerhalb des Codes.
