name: 🧷 Auto-Board: PR ins Projekt

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-pr-to-board:
    runs-on: ubuntu-latest
    steps:
      - name: ➕ Add PR to project board
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/mumibo-de/projects/8
          github-token: ${{ secrets.GITHUB_TOKEN }}
